version: '3.6'

networks:
  postgraphql:
    external: true

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5431:80"
    networks:
      - postgraphql

  postgresql:
    container_name: postgresql
    build:
      context: postgresql
    env_file:
      - ./.env
    ports:
      - published: 5432
        target: 5432
    networks:
      - postgraphql

  hasura:
    container_name: hasura
    image: hasura/graphql-engine:latest
    ports:
      - "5430:8080"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "${DATABASE_URL}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "${HASURA_GRAPHQL_ENABLE_CONSOLE}"
      HASURA_GRAPHQL_DEV_MODE: "${HASURA_GRAPHQL_DEV_MODE}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
    networks:
      - postgraphql
